#!/bin/bash

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install everything else
brew tap homebrew/services
brew install aria2
brew install carthage
brew install ctags
brew install ffmpeg
brew install git
brew install heroku
brew install hugo
brew install imagemagick
brew install mecab
brew install mecab-ipadic
brew install mitmproxy
brew install nginx
brew install nkf
brew install node
brew install pandoc
brew install ssh-copy-id
brew install the_silver_searcher
brew install tig
brew install tmux
brew install tree
brew install vim
brew install yarn

# Remove outdated versions from the cellar
brew cleanup
